### ISSUE TITLE
[Question] Log Slider v.s. Regular Slider

### ISSUE THREAD

**Issue by lcb931023** [obijywk/neural-style-server#2]
Just curious about the design decision of making slider control the values exponentially. Is it just because it fits how the parameters impact the final result better? From our experience we found that small changes gave us the controls we needed.

**Comment by obijywk** [comment]
Yeah, the idea was that small changes near the bottom of the scale had more impact than large changes near the top of the scale. I didn't measure this rigorously though, my assumption could be wrong.

**Comment by lcb931023** [comment]
Interesting observation ^_^ We'll experiment with it in our fork. Thanks.
